
### @name = "Get all products"
GET http://localhost:8080/api/products
Accept: application/json

### @name = "Get all products by price range"
GET http://localhost:8080/api/products?low=500&high=20000
Accept: application/json

### @name= Get product by ID
GET http://localhost:8080/api/products/2
Accept: application/json



### @name = Insert a Product
POST http://localhost:8080/api/products
Accept: application/json
Content-type: application/json

{
"name": "American Tourister",
"price": 2500.50,
"quantity": 100
}


### @name = Insert invalid  Product
POST http://localhost:8080/api/products
Accept: application/json
Content-type: application/json

{
  "name": "",
  "price": 0.50,
  "quantity": 0
}
